import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">ShowroomBuyurtmalarstatus</Link>
        </li>
        <li>
          <Link to="/omborbichishvarenderfour">OmborBichishvarenderFour</Link>
        </li>
        <li>
          <Link to="/omborbichishvarender">OmborBichishvarender</Link>
        </li>
        <li>
          <Link to="/omborbichishvarenderthree">OmborBichishvarenderThree</Link>
        </li>
        <li>
          <Link to="/omborbichishvarendertwo">OmborBichishvarenderTwo</Link>
        </li>
        <li>
          <Link to="/omborbichishvarendernine">OmborBichishvarenderNine</Link>
        </li>
        <li>
          <Link to="/omborbichishvarenderten">OmborBichishvarenderTen</Link>
        </li>
        <li>
          <Link to="/omborbichishvarendereleven">
            OmborBichishvarenderEleven
          </Link>
        </li>
        <li>
          <Link to="/omborbuyurtmalarroyhatitwo">
            OmborBuyurtmalarroyhatiTwo
          </Link>
        </li>
        <li>
          <Link to="/omborbuyurtmalarroyhatifour">
            OmborBuyurtmalarroyhatiFour
          </Link>
        </li>
        <li>
          <Link to="/royhatgaolishthree">RoyhatgaolishThree</Link>
        </li>
        <li>
          <Link to="/royhatgaolishfour">RoyhatgaolishFour</Link>
        </li>
        <li>
          <Link to="/omborbichishvarendertwelve">
            OmborBichishvarenderTwelve
          </Link>
        </li>
        <li>
          <Link to="/omborbichishvarenderthirteen">
            OmborBichishvarenderThirteen
          </Link>
        </li>
        <li>
          <Link to="/omborbichishvarenderfourteen">
            OmborBichishvarenderFourteen
          </Link>
        </li>
        <li>
          <Link to="/omborbuyurtmalarroyhati">OmborBuyurtmalarroyhati</Link>
        </li>
        <li>
          <Link to="/omborbuyurtmalarroyhatithree">
            OmborBuyurtmalarroyhatiThree
          </Link>
        </li>
        <li>
          <Link to="/ombortaminotchigazayavkaone">
            OmborTaminotchigazayavkaOne
          </Link>
        </li>
        <li>
          <Link to="/ombortaminotchigazayavka">OmborTaminotchigazayavka</Link>
        </li>
        <li>
          <Link to="/omborbuyurtmalarroyhatione">
            OmborBuyurtmalarroyhatiOne
          </Link>
        </li>
        <li>
          <Link to="/menu">Menu</Link>
        </li>
        <li>
          <Link to="/frameforty">FrameForty</Link>
        </li>
        <li>
          <Link to="/framefiftytwo">FrameFiftyTwo</Link>
        </li>
        <li>
          <Link to="/omborqoldiqidsi">OmborQoldiqIdsi</Link>
        </li>
        <li>
          <Link to="/omborqoldiqidsibuyurtmalarroyhati">
            OmborQoldiqIdsiBuyurtmalarroyhati
          </Link>
        </li>
        <li>
          <Link to="/ombormahsulotqabuliprofil">OmborMahsulotqabuliprofil</Link>
        </li>
        <li>
          <Link to="/ombormahsulotqabuliaksesuar">
            OmborMahsulotqabuliAksesuar
          </Link>
        </li>
        <li>
          <Link to="/omborqabultarixibuyurtmalartarkibi">
            OmborQabultarixiBuyurtmalartarkibi
          </Link>
        </li>
        <li>
          <Link to="/omborqabultarixibuyurtmalarroyhati">
            OmborQabultarixiBuyurtmalarroyhati
          </Link>
        </li>
        <li>
          <Link to="/omborqabultarixibuyurtmalarroyhatione">
            OmborQabultarixiBuyurtmalarroyhatiOne
          </Link>
        </li>
        <li>
          <Link to="/omborqabultarixibuyurtmalarroyhatitwo">
            OmborQabultarixiBuyurtmalarroyhatiTwo
          </Link>
        </li>
        <li>
          <Link to="/omborqabultarixibuyurtmalarroyhatithree">
            OmborQabultarixiBuyurtmalarroyhatiThree
          </Link>
        </li>
        <li>
          <Link to="/ombormahsulotlaromborione">OmborMahsulotlaromboriOne</Link>
        </li>
        <li>
          <Link to="/ombormahsulotlarombori">OmborMahsulotlarombori</Link>
        </li>
        <li>
          <Link to="/royhatgaolishfive">RoyhatgaolishFive</Link>
        </li>
        <li>
          <Link to="/royhatgaolishtwo">RoyhatgaolishTwo</Link>
        </li>
        <li>
          <Link to="/direktordashboard">DirektorDashboard</Link>
        </li>
        <li>
          <Link to="/royhatgaolishseven">RoyhatgaolishSeven</Link>
        </li>
        <li>
          <Link to="/royhatgaolish">Royhatgaolish</Link>
        </li>
        <li>
          <Link to="/royhatgaolishsix">RoyhatgaolishSix</Link>
        </li>
        <li>
          <Link to="/showroomdashboard">ShowroomDashboard</Link>
        </li>
        <li>
          <Link to="/moliyadashboard">MoliyaDashboard</Link>
        </li>
        <li>
          <Link to="/royhatgaolishone">RoyhatgaolishOne</Link>
        </li>
        <li>
          <Link to="/royhatgaolisheight">RoyhatgaolishEight</Link>
        </li>
        <li>
          <Link to="/ombormahsulotchiqimiprofillar">
            OmborMahsulotChiqimiprofillar
          </Link>
        </li>
        <li>
          <Link to="/ombormahsulotchiqimiaksesuar">
            Ombormahsulotchiqimiaksesuar
          </Link>
        </li>
        <li>
          <Link to="/omborchiqimtarixi">OmborChiqimtarixi</Link>
        </li>
        <li>
          <Link to="/omborchiqimtarixibuyurtmalartarkibi">
            OmborChiqimtarixiBuyurtmalartarkibi
          </Link>
        </li>
        <li>
          <Link to="/moliyakassa">MoliyaKassa</Link>
        </li>
        <li>
          <Link to="/showroombuyurtmayaratishone">
            ShowroomBuyurtmayaratishOne
          </Link>
        </li>
        <li>
          <Link to="/showroombuyurtmayaratish">ShowroomBuyurtmayaratish</Link>
        </li>
        <li>
          <Link to="/showroombuyurtmayaratishthree">
            ShowroomBuyurtmayaratishThree
          </Link>
        </li>
        <li>
          <Link to="/showroombuyurtmayaratishtwo">
            ShowroomBuyurtmayaratishTwo
          </Link>
        </li>
        <li>
          <Link to="/showroomishlabchiqarishda">ShowroomIshlabchiqarishda</Link>
        </li>
        <li>
          <Link to="/showroomishlabchiqarishdaone">
            ShowroomIshlabchiqarishdaOne
          </Link>
        </li>
        <li>
          <Link to="/showroombuyurtmalartarixi">ShowroomBuyurtmalartarixi</Link>
        </li>
        <li>
          <Link to="/plugin">Plugin</Link>
        </li>
        <li>
          <Link to="/showroombuyurtmalarstatusone">
            ShowroomBuyurtmalarstatusOne
          </Link>
        </li>
        <li>
          <Link to="/showroommijozlarroyhati">ShowroomMijozlarroyhati</Link>
        </li>
        <li>
          <Link to="/showroomroyhatgaolish">ShowroomRoyhatgaolish</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishfour">MoliyaKirimqilishFour</Link>
        </li>
        <li>
          <Link to="/moliyakirimtarixi">MoliyaKirimtarixi</Link>
        </li>
        <li>
          <Link to="/moliyashowroomdankirimtarixi">
            MoliyaShowroomdankirimtarixi
          </Link>
        </li>
        <li>
          <Link to="/kassaone">KassaOne</Link>
        </li>
        <li>
          <Link to="/kassatwo">KassaTwo</Link>
        </li>
        <li>
          <Link to="/kassa">Kassa</Link>
        </li>
        <li>
          <Link to="/showroomtolovlarhisobi">Showroomtolovlarhisobi</Link>
        </li>
        <li>
          <Link to="/showroomtolovqabulqilish">Showroomtolovqabulqilish</Link>
        </li>
        <li>
          <Link to="/showroomumumiytolovtarixi">Showroomumumiytolovtarixi</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilish">MoliyaKirimqilish</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishone">MoliyaKirimqilishOne</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishfive">MoliyaKirimqilishFive</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishthree">MoliyaKirimqilishThree</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishseven">MoliyaKirimqilishSeven</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilisheight">MoliyaKirimqilishEight</Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishtwo">MoliyaKirimqilishTwo</Link>
        </li>
        <li>
          <Link to="/omborqoldiqidsibuyurtmalarroyhatione">
            OmborQoldiqIdsiBuyurtmalarroyhatiOne
          </Link>
        </li>
        <li>
          <Link to="/moliyakirimqilishsix">MoliyaKirimqilishSix</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixieight">MoliyaChiqimtarixiEight</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixiten">MoliyaChiqimtarixiTen</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixisix">MoliyaChiqimtarixiSix</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixifour">MoliyaChiqimtarixiFour</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixiseven">MoliyaChiqimtarixiSeven</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixinine">MoliyaChiqimtarixiNine</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixitwo">MoliyaChiqimtarixiTwo</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixifive">MoliyaChiqimtarixiFive</Link>
        </li>
        <li>
          <Link to="/moliyabuyurtmagachiqimtarixi">
            MoliyaBuyurtmagachiqimtarixi
          </Link>
        </li>
        <li>
          <Link to="/moliyabuyurtmagachiqimtarixidavomi">
            MoliyaBuyurtmagachiqimtarixidavomi
          </Link>
        </li>
        <li>
          <Link to="/moliyakirimtarixione">MoliyaKirimtarixiOne</Link>
        </li>
        <li>
          <Link to="/moliyashowroomdankirimtarixitwo">
            MoliyaShowroomdankirimtarixiTwo
          </Link>
        </li>
        <li>
          <Link to="/moliyashowroomdankirimtarixione">
            MoliyaShowroomdankirimtarixiOne
          </Link>
        </li>
        <li>
          <Link to="/savdobolimibuyurtmalarroyhati">
            Savdobolimibuyurtmalarroyhati
          </Link>
        </li>
        <li>
          <Link to="/buyurtmalarone">BuyurtmalarOne</Link>
        </li>
        <li>
          <Link to="/buyurtmalar">Buyurtmalar</Link>
        </li>
        <li>
          <Link to="/buyurtmalartwo">BuyurtmalarTwo</Link>
        </li>
        <li>
          <Link to="/royhatgaolishnine">RoyhatgaolishNine</Link>
        </li>
        <li>
          <Link to="/royhatgaolishten">RoyhatgaolishTen</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixi">MoliyaChiqimtarixi</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixithree">MoliyaChiqimtarixiThree</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixione">MoliyaChiqimtarixiOne</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixififteen">MoliyaChiqimtarixiFifteen</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixifourteen">
            MoliyaChiqimtarixiFourteen
          </Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixieleven">MoliyaChiqimtarixiEleven</Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixithirteen">
            MoliyaChiqimtarixiThirteen
          </Link>
        </li>
        <li>
          <Link to="/moliyachiqimtarixitwelve">MoliyaChiqimtarixiTwelve</Link>
        </li>
        <li>
          <Link to="/moliyavalyutaayriboshlash">MoliyaValyutaayriboshlash</Link>
        </li>
        <li>
          <Link to="/moliyavalyutaayriboshlashtarixi">
            MoliyaValyutaayriboshlashtarixi
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexijoriybuyurtmalar">
            IshlabchiqarishsexiJoriybuyurtmalar
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexijoriybuyurtmalarone">
            IshlabchiqarishsexiJoriybuyurtmalarOne
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexijoriybuyurtmalartwo">
            IshlabchiqarishsexiJoriybuyurtmalarTwo
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexijoriybuyurtmalarthree">
            IshlabchiqarishsexiJoriybuyurtmalarThree
          </Link>
        </li>
        <li>
          <Link to="/royhatgaolishtwelve">RoyhatgaolishTwelve</Link>
        </li>
        <li>
          <Link to="/royhatgaolishthirteen">RoyhatgaolishThirteen</Link>
        </li>
        <li>
          <Link to="/savdobolimibuyurtmalarroyhatione">
            SavdobolimibuyurtmalarroyhatiOne
          </Link>
        </li>
        <li>
          <Link to="/savdobolimibuyurtmauchunzayavka">
            Savdobolimibuyurtmauchunzayavka
          </Link>
        </li>
        <li>
          <Link to="/buyurtmalarthree">BuyurtmalarThree</Link>
        </li>
        <li>
          <Link to="/buyurtmalarfour">BuyurtmalarFour</Link>
        </li>
        <li>
          <Link to="/moliyabuyurtmagachiqimtarixione">
            MoliyaBuyurtmagachiqimtarixiOne
          </Link>
        </li>
        <li>
          <Link to="/moliyabuyurtmagachiqimtarixidavomione">
            MoliyaBuyurtmagachiqimtarixidavomiOne
          </Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatisix">MoliyaHodimlarroyhatiSix</Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibuyurtmaqoldiqid">
            IshlabchiqarishsexiBuyurtmaqoldiqID
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibuyurtmaqoldiqidbuyurtmanomeri">
            IshlabchiqarishsexiBuyurtmaqoldiqIDbuyurtmanomeri
          </Link>
        </li>
        <li>
          <Link to="/savdobolimitolovqabuli">Savdobolimitolovqabuli</Link>
        </li>
        <li>
          <Link to="/savdobolimitolovhisobi">Savdobolimitolovhisobi</Link>
        </li>
        <li>
          <Link to="/savdobolimitolovtarixi">Savdobolimitolovtarixi</Link>
        </li>
        <li>
          <Link to="/showroommijozlarroyhatione">
            ShowroomMijozlarroyhatiOne
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobiseven">
            IshlabchiqarishsexiBrakmahsulotlarhisobiSeven
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexione">IshlabchiqarishsexiOne</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhati">MoliyaHodimlarroyhati</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatifive">MoliyaHodimlarroyhatiFive</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatieight">
            MoliyaHodimlarroyhatiEight
          </Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatiten">MoliyaHodimlarroyhatiTen</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatieleven">
            MoliyaHodimlarroyhatiEleven
          </Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatiseven">
            MoliyaHodimlarroyhatiSeven
          </Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatifour">MoliyaHodimlarroyhatiFour</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatione">MoliyaHodimlarroyhatiOne</Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobithree">
            IshlabchiqarishsexiBrakmahsulotlarhisobiThree
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobisix">
            IshlabchiqarishsexiBrakmahsulotlarhisobiSix
          </Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatinine">MoliyaHodimlarroyhatiNine</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatitwo">MoliyaHodimlarroyhatiTwo</Link>
        </li>
        <li>
          <Link to="/moliyahodimlarroyhatithree">
            MoliyaHodimlarroyhatiThree
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobieleven">
            IshlabchiqarishsexiBrakmahsulotlarhisobiEleven
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobiten">
            IshlabchiqarishsexiBrakmahsulotlarhisobiTen
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexi">Ishlabchiqarishsexi</Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobinine">
            IshlabchiqarishsexiBrakmahsulotlarhisobiNine
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobifour">
            IshlabchiqarishsexiBrakmahsulotlarhisobiFour
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobifive">
            IshlabchiqarishsexiBrakmahsulotlarhisobiFive
          </Link>
        </li>
        <li>
          <Link to="/royhatgaolisheleven">RoyhatgaolishEleven</Link>
        </li>
        <li>
          <Link to="/royhatgaolishfourteen">RoyhatgaolishFourteen</Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobieight">
            IshlabchiqarishsexiBrakmahsulotlarhisobiEight
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobi">
            IshlabchiqarishsexiBrakmahsulotlarhisobi
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobitwo">
            IshlabchiqarishsexiBrakmahsulotlarhisobiTwo
          </Link>
        </li>
        <li>
          <Link to="/ishlabchiqarishsexibrakmahsulotlarhisobione">
            IshlabchiqarishsexiBrakmahsulotlarhisobiOne
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
